"use client";

import { useState } from "react";
import { useStore } from "@/store/useStore";

/**
 * Full pipeline dashboard: consensus, price targets, key arguments,
 * intelligence briefing, cross-examination results, and trade setup.
 * Shows ALL data generated by the 5-stage pipeline.
 */
export function RunStatsTab() {
  const debate = useStore((s) => s.currentDebate);
  const summary = debate?.summary;

  if (!summary) {
    return (
      <div className="flex h-full items-center justify-center text-xs" style={{ color: "var(--text-muted)" }}>
        Run a swarm debate to see run statistics
      </div>
    );
  }

  const dirColor =
    summary.consensusDirection === "BULLISH" ? "#22c55e"
    : summary.consensusDirection === "BEARISH" ? "#ef4444"
    : "#ff6b00";

  const rec = (summary.recommendation || {}) as Record<string, unknown>;
  const brief = debate.intelBriefing;
  const crossExam = (debate.crossExamResults || []) as import("@/types").CrossExamResult[];
  const convictionShifts: string[] = summary.convictionShifts || [];
  const marketContext = debate.marketContext;
  const dataFeeds = debate.dataFeeds || {};
  const timeline = debate.convergenceTimeline || [];
  const agentResearch = debate.agentResearch || {};
  const totalResearchQueries = Object.values(agentResearch).reduce((acc, arr) => acc + arr.length, 0);

  const [exporting, setExporting] = useState(false);

  const handleExportPDF = async () => {
    if (exporting) return;
    setExporting(true);
    try {
      // Lazy-load jsPDF so it stays out of the initial bundle
      const { default: jsPDF } = await import("jspdf");

      const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pageW = pdf.internal.pageSize.getWidth();
      const pageH = pdf.internal.pageSize.getHeight();
      const margin = 15;
      const contentW = pageW - margin * 2;
      let y = margin;

      // Colors (printable light theme — dark text on white)
      const TEXT: [number, number, number] = [30, 30, 35];
      const MUTED: [number, number, number] = [110, 110, 120];
      const ACCENT: [number, number, number] = [230, 85, 0];
      const BULL: [number, number, number] = [22, 140, 74];
      const BEAR: [number, number, number] = [200, 40, 40];
      const BORDER: [number, number, number] = [215, 215, 220];

      const setText = (rgb: [number, number, number]) => pdf.setTextColor(rgb[0], rgb[1], rgb[2]);
      const setFill = (rgb: [number, number, number]) => pdf.setFillColor(rgb[0], rgb[1], rgb[2]);

      const ensureSpace = (needed: number) => {
        if (y + needed > pageH - margin) {
          pdf.addPage();
          y = margin;
        }
      };

      const addTitle = (text: string, subtitle?: string) => {
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(22);
        setText(ACCENT);
        pdf.text(text, margin, y + 8);
        y += 10;
        if (subtitle) {
          pdf.setFont("helvetica", "normal");
          pdf.setFontSize(11);
          setText(TEXT);
          pdf.text(subtitle, margin, y + 5);
          y += 7;
        }
      };

      const addHeading = (text: string) => {
        ensureSpace(14);
        y += 4;
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(13);
        setText(TEXT);
        pdf.text(text, margin, y + 5);
        y += 7;
        setFill(ACCENT);
        pdf.rect(margin, y, 18, 0.6, "F");
        setFill(BORDER);
        pdf.rect(margin + 18, y, contentW - 18, 0.3, "F");
        y += 3;
      };

      const addSubheading = (text: string) => {
        ensureSpace(7);
        y += 2;
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(9);
        setText(MUTED);
        pdf.text(text.toUpperCase(), margin, y + 3);
        y += 5;
      };

      const addParagraph = (text: string, indent = 0) => {
        if (!text) return;
        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(9.5);
        setText(TEXT);
        const lines = pdf.splitTextToSize(text, contentW - indent) as string[];
        const lineH = 4.5;
        for (const line of lines) {
          ensureSpace(lineH);
          pdf.text(line, margin + indent, y + 3);
          y += lineH;
        }
        y += 1;
      };

      const addBullet = (text: string) => {
        if (!text) return;
        const indent = 5;
        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(9.5);
        const lines = pdf.splitTextToSize(text, contentW - indent - 3) as string[];
        const lineH = 4.5;
        ensureSpace(lineH);
        setText(ACCENT);
        pdf.text("•", margin + 1, y + 3);
        setText(TEXT);
        for (let i = 0; i < lines.length; i++) {
          if (i > 0) ensureSpace(lineH);
          pdf.text(lines[i], margin + indent, y + 3);
          y += lineH;
        }
        y += 0.5;
      };

      const addKV = (key: string, value: string, valueColor?: [number, number, number]) => {
        if (!value) return;
        const keyW = 50;
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(9);
        setText(MUTED);
        const keyLines = pdf.splitTextToSize(key, keyW - 2) as string[];
        pdf.setFont("helvetica", "normal");
        const valueLines = pdf.splitTextToSize(value, contentW - keyW) as string[];
        const lineH = 4.2;
        const blockH = Math.max(keyLines.length, valueLines.length) * lineH;
        ensureSpace(blockH + 1);
        pdf.setFont("helvetica", "bold");
        setText(MUTED);
        pdf.text(keyLines, margin, y + 3);
        pdf.setFont("helvetica", "normal");
        setText(valueColor || TEXT);
        pdf.text(valueLines, margin + keyW, y + 3);
        y += blockH + 1;
      };

      const addDivider = () => {
        ensureSpace(3);
        setFill(BORDER);
        pdf.rect(margin, y + 1, contentW, 0.2, "F");
        y += 3;
      };

      // ─── Cover ────────────────────────────────────────────────
      addTitle("Swarm Debate Report", `${debate.assetName || debate.symbol}${debate.symbol && debate.assetName !== debate.symbol ? ` (${debate.symbol})` : ""}`);
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(9);
      setText(MUTED);
      pdf.text(
        `${debate.assetClass} · ${debate.entities.length} personas · ${debate.totalRounds} rounds · ${debate.thread.length} messages`,
        margin, y + 4,
      );
      y += 5;
      pdf.text(`Generated ${new Date().toLocaleString()}`, margin, y + 4);
      y += 8;

      // Consensus banner
      const dirRgb = summary.consensusDirection === "BULLISH" ? BULL : summary.consensusDirection === "BEARISH" ? BEAR : ACCENT;
      setFill(dirRgb);
      pdf.rect(margin, y, contentW, 22, "F");
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(20);
      pdf.setTextColor(255, 255, 255);
      pdf.text(`CONSENSUS: ${summary.consensusDirection}`, margin + 5, y + 10);
      pdf.setFontSize(12);
      pdf.text(`${summary.confidence.toFixed(0)}% confidence`, margin + 5, y + 18);
      y += 26;

      // ─── Trade Recommendation ──────────────────────────────────
      if (rec.action || summary.priceTargets) {
        addHeading("Trade Recommendation");
        if (rec.action) addKV("Action", String(rec.action).toUpperCase(), dirRgb);
        if (rec.entry != null) addKV("Entry", `$${Number(rec.entry).toLocaleString()}`);
        if (rec.stop != null) addKV("Stop Loss", `$${Number(rec.stop).toLocaleString()}`, BEAR);
        if (rec.target != null) addKV("Target", `$${Number(rec.target).toLocaleString()}`, BULL);
        if (rec.position_size_pct != null) addKV("Position Size", `${String(rec.position_size_pct)}%`);

        if (summary.priceTargets) {
          addSubheading("Price Targets");
          addKV("Low", `$${Number(summary.priceTargets.low).toLocaleString()}`, BEAR);
          addKV("Mid", `$${Number(summary.priceTargets.mid).toLocaleString()}`);
          addKV("High", `$${Number(summary.priceTargets.high).toLocaleString()}`, BULL);
        }
      }

      // ─── Key Arguments ────────────────────────────────────────
      if (summary.keyArguments?.length) {
        addHeading("Key Arguments (Debate)");
        summary.keyArguments.forEach((a) => addBullet(a));
      }

      // ─── Dissenting Views ─────────────────────────────────────
      if (summary.dissentingViews?.length) {
        addHeading("Dissenting Views");
        summary.dissentingViews.forEach((v) => addBullet(v));
      }

      // ─── Risk Factors ─────────────────────────────────────────
      if (summary.riskFactors?.length) {
        addHeading("Risk Factors");
        summary.riskFactors.forEach((r) => addBullet(r));
      }

      // ─── Conviction Shifts ────────────────────────────────────
      if (convictionShifts.length) {
        addHeading("Conviction Shifts During Debate");
        convictionShifts.forEach((s) => addBullet(s));
      }

      // ─── Intelligence Briefing ────────────────────────────────
      if (brief && (brief.executiveSummary || brief.bullCase?.length || brief.bearCase?.length)) {
        addHeading("Intelligence Briefing (Stage 1.5)");

        if (brief.executiveSummary) {
          addSubheading("Executive Summary");
          addParagraph(brief.executiveSummary);
        }
        if (brief.sentimentReading) {
          addKV("Market Sentiment", brief.sentimentReading, dirRgb);
        }
        if (brief.bullCase?.length) {
          addSubheading("Bull Case");
          brief.bullCase.forEach((b) => addBullet(b));
        }
        if (brief.bearCase?.length) {
          addSubheading("Bear Case");
          brief.bearCase.forEach((b) => addBullet(b));
        }
        if (brief.keyEvents?.length) {
          addSubheading("Upcoming Key Events");
          brief.keyEvents.forEach((e) => addBullet(e));
        }
        if (brief.dataPoints?.length) {
          addSubheading("Key Data Points");
          brief.dataPoints.forEach((d) => addBullet(d));
        }
      }

      // ─── Market Context ───────────────────────────────────────
      if (marketContext) {
        addHeading("Market Context (Stage 1)");
        if (marketContext.marketRegime) addKV("Market Regime", marketContext.marketRegime, dirRgb);
        if (marketContext.volumeAnalysis) addKV("Volume Analysis", marketContext.volumeAnalysis);
        if (marketContext.keyPriceLevels) {
          const kpl = marketContext.keyPriceLevels;
          if (kpl.strongResistance?.length) {
            addKV("Strong Resistance", kpl.strongResistance.map((n) => `$${Number(n).toLocaleString()}`).join(", "), BEAR);
          }
          if (kpl.strongSupport?.length) {
            addKV("Strong Support", kpl.strongSupport.map((n) => `$${Number(n).toLocaleString()}`).join(", "), BULL);
          }
          if (kpl.recentPivot != null) addKV("Recent Pivot", String(kpl.recentPivot));
        }
        if (marketContext.technicalSignals?.length) {
          addSubheading("Technical Signals");
          marketContext.technicalSignals.forEach((s) => addBullet(s));
        }
        if (marketContext.keyThemes?.length) {
          addSubheading("Key Themes");
          marketContext.keyThemes.forEach((t) => addBullet(t));
        }
        if (marketContext.riskEvents?.length) {
          addSubheading("Risk Events");
          marketContext.riskEvents.forEach((r) => addBullet(r));
        }
      }

      // ─── Data Feeds ───────────────────────────────────────────
      const feedEntries = Object.entries(dataFeeds).filter(([, v]) => !!v);
      if (feedEntries.length) {
        addHeading("Data Feeds");
        feedEntries.forEach(([key, value]) => {
          addSubheading(key.replace(/_/g, " "));
          addParagraph(String(value));
        });
      }

      // ─── Raw Research Findings ────────────────────────────────
      if (brief?.rawFindings) {
        const rf = brief.rawFindings;
        const any = rf.recentNews || rf.marketAnalysis || rf.regulatory || rf.technicalIndicators || rf.keyLevels;
        if (any) {
          addHeading("Raw Research Findings");
          if (rf.recentNews) {
            addSubheading("Recent News");
            addParagraph(rf.recentNews);
          }
          if (rf.technicalIndicators) {
            addSubheading("Technical Indicators");
            addParagraph(rf.technicalIndicators);
          }
          if (rf.keyLevels) {
            addSubheading("Key Price Levels");
            addParagraph(rf.keyLevels);
          }
          if (rf.marketAnalysis) {
            addSubheading("Market Analysis");
            addParagraph(rf.marketAnalysis);
          }
          if (rf.regulatory) {
            addSubheading("Regulatory");
            addParagraph(rf.regulatory);
          }
        }
      }

      // ─── Cross-Examination ────────────────────────────────────
      if (crossExam.length) {
        addHeading(`Cross-Examination (${crossExam.length} agents)`);
        crossExam.forEach((ex, i) => {
          if (i > 0) addDivider();
          ensureSpace(8);
          pdf.setFont("helvetica", "bold");
          pdf.setFontSize(10.5);
          setText(TEXT);
          pdf.text(ex.entityName || "(unknown)", margin, y + 3);
          pdf.setFont("helvetica", "normal");
          pdf.setFontSize(8.5);
          setText(ACCENT);
          if (ex.entityRole) pdf.text(ex.entityRole, margin + 65, y + 3);

          const convColor =
            ex.convictionChange === "reversed" ? BEAR :
            ex.convictionChange === "weakened" ? BEAR :
            ex.convictionChange === "strengthened" ? BULL :
            MUTED;
          pdf.setFont("helvetica", "bold");
          pdf.setFontSize(8);
          setText(convColor);
          pdf.text(String(ex.convictionChange || "unchanged").toUpperCase(), pageW - margin - 30, y + 3);
          y += 6;

          if (ex.question) {
            addSubheading("Question");
            addParagraph(ex.question);
          }
          if (ex.response) {
            addSubheading("Response");
            addParagraph(ex.response);
          }
          if (ex.newSentiment != null) {
            const sc = ex.newSentiment > 0.2 ? BULL : ex.newSentiment < -0.2 ? BEAR : MUTED;
            addKV("New Sentiment", `${(ex.newSentiment * 100).toFixed(0)}%`, sc);
          }
        });
      }

      // ─── Convergence Timeline ─────────────────────────────────
      if (timeline.length) {
        addHeading("Sentiment Convergence Timeline");
        addParagraph("Weighted average sentiment at the end of each round (positive = bullish, negative = bearish):");
        timeline.forEach((pt) => {
          const sc = pt.sentiment > 0.2 ? BULL : pt.sentiment < -0.2 ? BEAR : MUTED;
          const label = pt.sentiment > 0 ? `+${(pt.sentiment * 100).toFixed(1)}%` : `${(pt.sentiment * 100).toFixed(1)}%`;
          addKV(`Round ${pt.round}`, label, sc);
        });
      }

      // ─── Agent Research Trail ─────────────────────────────────
      if (totalResearchQueries > 0) {
        addHeading(`Agent Research Trail (${totalResearchQueries} queries)`);
        addParagraph(`${Object.keys(agentResearch).length} agents performed iterative research, averaging ${(totalResearchQueries / Object.keys(agentResearch).length).toFixed(1)} queries each.`);

        Object.entries(agentResearch).forEach(([entityId, findings]) => {
          if (!findings?.length) return;
          const entity = debate.entities.find((e) => e.id === entityId);
          const entityName = entity?.name || entityId;

          ensureSpace(8);
          y += 2;
          pdf.setFont("helvetica", "bold");
          pdf.setFontSize(10);
          setText(TEXT);
          pdf.text(`${entityName}`, margin, y + 3);
          pdf.setFont("helvetica", "normal");
          pdf.setFontSize(8.5);
          setText(MUTED);
          pdf.text(`${findings.length} queries`, pageW - margin - 25, y + 3);
          y += 5;

          findings.forEach((f, idx) => {
            const header = `#${f.iteration || idx + 1}  [${f.tool}]  "${f.query}"`;
            pdf.setFont("helvetica", "bold");
            pdf.setFontSize(8.5);
            setText(ACCENT);
            const hLines = pdf.splitTextToSize(header, contentW - 4) as string[];
            for (const hl of hLines) {
              ensureSpace(3.8);
              pdf.text(hl, margin + 3, y + 2.5);
              y += 3.8;
            }
            if (f.reasoning) {
              pdf.setFont("helvetica", "italic");
              setText(MUTED);
              const rLines = pdf.splitTextToSize(`Reasoning: ${f.reasoning}`, contentW - 6) as string[];
              for (const rl of rLines) {
                ensureSpace(3.5);
                pdf.text(rl, margin + 5, y + 2.5);
                y += 3.5;
              }
            }
            if (f.result) {
              pdf.setFont("helvetica", "normal");
              setText(TEXT);
              const rLines = pdf.splitTextToSize(f.result.slice(0, 600), contentW - 6) as string[];
              for (const rl of rLines) {
                ensureSpace(3.8);
                pdf.text(rl, margin + 5, y + 2.5);
                y += 3.8;
              }
            }
            y += 1;
          });
        });
      }

      // ─── Personas ─────────────────────────────────────────────
      if (debate.entities?.length) {
        addHeading(`Personas (${debate.entities.length})`);
        debate.entities.forEach((ent, i) => {
          if (i > 0) addDivider();
          ensureSpace(8);
          pdf.setFont("helvetica", "bold");
          pdf.setFontSize(10.5);
          setText(TEXT);
          pdf.text(ent.name, margin, y + 3);
          pdf.setFont("helvetica", "normal");
          pdf.setFontSize(8.5);
          setText(ACCENT);
          pdf.text(ent.role, margin + 55, y + 3);
          if (ent.stance) {
            const sc = ent.stance === "bull" ? BULL : ent.stance === "bear" ? BEAR : MUTED;
            pdf.setFont("helvetica", "bold");
            pdf.setFontSize(8);
            setText(sc);
            pdf.text(ent.stance.toUpperCase(), pageW - margin - 20, y + 3);
          }
          y += 5;

          if (ent.specialization) addKV("Specialization", ent.specialization);
          if (ent.influence != null) addKV("Influence", `${ent.influence.toFixed(2)}x`);
          if (ent.tools?.length) addKV("Tools", ent.tools.join(", "));
          if (ent.background) addParagraph(ent.background, 2);
          if (ent.personality) {
            pdf.setFont("helvetica", "italic");
            pdf.setFontSize(9);
            setText(MUTED);
            const lines = pdf.splitTextToSize(`Personality: ${ent.personality}`, contentW - 2) as string[];
            for (const line of lines) {
              ensureSpace(4.2);
              pdf.text(line, margin + 2, y + 3);
              y += 4.2;
            }
          }
          if (ent.bias) {
            pdf.setFont("helvetica", "italic");
            pdf.setFontSize(9);
            setText(MUTED);
            const lines = pdf.splitTextToSize(`Bias: ${ent.bias}`, contentW - 2) as string[];
            for (const line of lines) {
              ensureSpace(4.2);
              pdf.text(line, margin + 2, y + 3);
              y += 4.2;
            }
          }
          y += 1;
        });
      }

      // ─── Full Debate Thread ──────────────────────────────────
      if (debate.thread?.length) {
        addHeading(`Full Debate Thread (${debate.thread.length} messages)`);
        debate.thread.forEach((msg, i) => {
          if (i > 0) y += 1.5;
          ensureSpace(8);
          pdf.setFont("helvetica", "bold");
          pdf.setFontSize(9.5);
          setText(TEXT);
          pdf.text(`R${msg.round}  ${msg.entityName}`, margin, y + 3);
          pdf.setFont("helvetica", "normal");
          pdf.setFontSize(8);
          setText(ACCENT);
          pdf.text(msg.entityRole, margin + 65, y + 3);
          const sc = msg.sentiment > 0.2 ? BULL : msg.sentiment < -0.2 ? BEAR : MUTED;
          const sentTxt = msg.sentiment > 0 ? `+${(msg.sentiment * 100).toFixed(0)}%` : `${(msg.sentiment * 100).toFixed(0)}%`;
          pdf.setFont("helvetica", "bold");
          setText(sc);
          pdf.text(sentTxt, pageW - margin - 15, y + 3);
          y += 5;

          addParagraph(msg.content);

          const footer: string[] = [];
          if (msg.pricePrediction != null) footer.push(`Target $${Number(msg.pricePrediction).toLocaleString()}`);
          if (msg.agreedWith?.length) footer.push(`Agrees: ${msg.agreedWith.join(", ")}`);
          if (msg.disagreedWith?.length) footer.push(`Disagrees: ${msg.disagreedWith.join(", ")}`);
          if (msg.toolsUsed?.length) footer.push(`Tools: ${msg.toolsUsed.join(", ")}`);
          if (msg.isChartSupport) footer.push("[chart data injected]");
          if (footer.length) {
            pdf.setFont("helvetica", "italic");
            pdf.setFontSize(7.5);
            setText(MUTED);
            const lines = pdf.splitTextToSize(footer.join(" · "), contentW) as string[];
            for (const line of lines) {
              ensureSpace(3.3);
              pdf.text(line, margin, y + 2.2);
              y += 3.3;
            }
          }
        });
      }

      // ─── Page numbers + footer ────────────────────────────────
      const pageCount = pdf.getNumberOfPages();
      for (let p = 1; p <= pageCount; p++) {
        pdf.setPage(p);
        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(8);
        setText(MUTED);
        pdf.text(`Swarm Debate · ${debate.assetName || debate.symbol}`, margin, pageH - 8);
        pdf.text(`Page ${p} of ${pageCount}`, pageW - margin - 24, pageH - 8);
      }

      const assetName = (debate.assetName || debate.symbol || "asset").replace(/[^a-zA-Z0-9_-]/g, "_");
      const date = new Date().toISOString().slice(0, 10);
      pdf.save(`swarm_debate_${assetName}_${date}.pdf`);
    } catch (err) {
      console.error("PDF export failed:", err);
      alert("PDF export failed: " + (err instanceof Error ? err.message : String(err)));
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="h-full overflow-y-auto p-3 space-y-3">
      {/* Export header */}
      <div className="flex items-center gap-2 -mb-1">
        <div className="text-[9px] font-bold uppercase tracking-wider" style={{ color: "var(--text-muted)" }}>
          {debate.assetName} · {debate.entities.length} personas · {debate.totalRounds} rounds
        </div>
        <button
          onClick={handleExportPDF}
          disabled={exporting}
          className="ml-auto flex items-center gap-1.5 rounded px-2.5 py-1 text-[10px] font-semibold transition-colors disabled:opacity-40"
          style={{
            background: exporting ? "var(--surface-2)" : "rgba(255, 107, 0, 0.12)",
            color: "var(--accent)",
            border: "1px solid rgba(255, 107, 0, 0.3)",
          }}
          title="Export full report as PDF"
        >
          <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          {exporting ? "Generating..." : "Export PDF"}
        </button>
      </div>

      <div className="rounded-lg p-3" style={{ background: "var(--surface-2)", border: "1px solid var(--border)" }}>
        <div className="text-[9px] font-bold uppercase tracking-wider mb-2" style={{ color: "var(--text-muted)" }}>
          Pipeline Data Available
        </div>
        <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-[10px] sm:grid-cols-3 lg:grid-cols-4">
          <DataStatus label="Intelligence Briefing" has={!!brief?.executiveSummary} />
          <DataStatus label="Bull Case" has={(brief?.bullCase?.length ?? 0) > 0} count={brief?.bullCase?.length} />
          <DataStatus label="Bear Case" has={(brief?.bearCase?.length ?? 0) > 0} count={brief?.bearCase?.length} />
          <DataStatus label="Key Events" has={(brief?.keyEvents?.length ?? 0) > 0} count={brief?.keyEvents?.length} />
          <DataStatus label="Data Points" has={(brief?.dataPoints?.length ?? 0) > 0} count={brief?.dataPoints?.length} />
          <DataStatus label="Cross-Exams" has={crossExam.length > 0} count={crossExam.length} />
          <DataStatus label="Conviction Shifts" has={convictionShifts.length > 0} count={convictionShifts.length} />
          <DataStatus label="Trade Recommendation" has={!!rec.action} />
          <DataStatus label="Raw News" has={!!brief?.rawFindings?.recentNews} />
          <DataStatus label="Tech Indicators" has={!!brief?.rawFindings?.technicalIndicators} />
          <DataStatus label="Regulatory" has={!!brief?.rawFindings?.regulatory} />
          <DataStatus label="Market Analysis" has={!!brief?.rawFindings?.marketAnalysis} />
          <DataStatus label="Market Context" has={!!marketContext?.marketRegime} />
          <DataStatus label="Technical Signals" has={(marketContext?.technicalSignals?.length ?? 0) > 0} count={marketContext?.technicalSignals?.length} />
          <DataStatus label="Key Themes" has={(marketContext?.keyThemes?.length ?? 0) > 0} count={marketContext?.keyThemes?.length} />
          <DataStatus label="Risk Events" has={(marketContext?.riskEvents?.length ?? 0) > 0} count={marketContext?.riskEvents?.length} />
          <DataStatus label="Data Feeds" has={Object.keys(dataFeeds).length > 0} count={Object.keys(dataFeeds).length} />
          <DataStatus label="Agent Research" has={totalResearchQueries > 0} count={totalResearchQueries} />
          <DataStatus label="Convergence Timeline" has={timeline.length > 0} count={timeline.length} />
        </div>
      </div>

      {/* Market Context (Stage 1 output — previously hidden) */}
      {marketContext && (
        <Card title="Market Context (Stage 1)" accent>
          <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
            {marketContext.marketRegime && (
              <div>
                <div className="text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: "var(--text-muted)" }}>Market Regime</div>
                <div className="text-[11px] font-bold" style={{ color: dirColor }}>{marketContext.marketRegime}</div>
              </div>
            )}
            {marketContext.volumeAnalysis && (
              <div>
                <div className="text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: "var(--text-muted)" }}>Volume Analysis</div>
                <div className="text-[10px]" style={{ color: "var(--text-secondary)" }}>{marketContext.volumeAnalysis}</div>
              </div>
            )}
            {marketContext.keyPriceLevels && (
              <div className="lg:col-span-2">
                <div className="text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: "var(--text-muted)" }}>Key Price Levels</div>
                <div className="flex gap-3 text-[10px]">
                  {marketContext.keyPriceLevels.strongResistance && marketContext.keyPriceLevels.strongResistance.length > 0 && (
                    <span><span style={{ color: "#ef4444" }}>Resistance:</span> {marketContext.keyPriceLevels.strongResistance.map(n => `$${Number(n).toLocaleString()}`).join(", ")}</span>
                  )}
                  {marketContext.keyPriceLevels.strongSupport && marketContext.keyPriceLevels.strongSupport.length > 0 && (
                    <span><span style={{ color: "#22c55e" }}>Support:</span> {marketContext.keyPriceLevels.strongSupport.map(n => `$${Number(n).toLocaleString()}`).join(", ")}</span>
                  )}
                </div>
              </div>
            )}
            {marketContext.technicalSignals && marketContext.technicalSignals.length > 0 && (
              <div>
                <div className="text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: "var(--text-muted)" }}>Technical Signals</div>
                <ul className="space-y-0.5 text-[10px]" style={{ color: "var(--text-secondary)" }}>
                  {marketContext.technicalSignals.map((s, i) => <li key={i}>• {s}</li>)}
                </ul>
              </div>
            )}
            {marketContext.keyThemes && marketContext.keyThemes.length > 0 && (
              <div>
                <div className="text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: "var(--text-muted)" }}>Key Themes</div>
                <div className="flex flex-wrap gap-1">
                  {marketContext.keyThemes.map((t, i) => (
                    <span key={i} className="rounded px-1.5 py-0.5 text-[9px]" style={{ background: "var(--surface)", color: "var(--text-secondary)", border: "1px solid var(--border)" }}>{t}</span>
                  ))}
                </div>
              </div>
            )}
            {marketContext.riskEvents && marketContext.riskEvents.length > 0 && (
              <div className="lg:col-span-2">
                <div className="text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: "var(--text-muted)" }}>Risk Events</div>
                <ul className="space-y-0.5 text-[10px]" style={{ color: "var(--text-secondary)" }}>
                  {marketContext.riskEvents.map((r, i) => <li key={i} className="flex gap-1"><span style={{ color: "#f59e0b" }}>!</span>{r}</li>)}
                </ul>
              </div>
            )}
          </div>
        </Card>
      )}

      {/* Convergence Timeline (sentiment per round) */}
      {timeline.length > 0 && (
        <Card title={`Sentiment Convergence (${timeline.length} rounds)`}>
          <ConvergenceChart timeline={timeline} />
        </Card>
      )}

      {/* Agent Research Summary */}
      {totalResearchQueries > 0 && (
        <Card title={`Iterative Research (${totalResearchQueries} queries across ${Object.keys(agentResearch).length} agents)`} accent>
          <div className="text-[10px]" style={{ color: "var(--text-secondary)" }}>
            Agents did deep research before the debate. Click any persona card in the Personalities tab to see each agent's full research trail with query reasoning and findings.
          </div>
          <div className="mt-2 text-[9px]" style={{ color: "var(--text-muted)" }}>
            Average per agent: {(totalResearchQueries / Object.keys(agentResearch).length).toFixed(1)} queries
          </div>
        </Card>
      )}
      <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
        <Card title="Consensus">
          <div className="flex items-baseline gap-3">
            <span className="rounded-md px-3 py-1 text-sm font-black uppercase tracking-wide" style={{ background: `${dirColor}22`, color: dirColor }}>
              {summary.consensusDirection}
            </span>
            <span className="text-2xl font-bold tabular-nums" style={{ color: "var(--text-primary)" }}>
              {summary.confidence.toFixed(0)}%
            </span>
          </div>
          <div className="mt-1 text-[10px]" style={{ color: "var(--text-muted)" }}>
            {debate.entities.length} personas, {debate.totalRounds} rounds, {debate.thread.length} messages
          </div>
        </Card>

        {summary.priceTargets && (
          <Card title="Price Targets">
            <div className="flex items-end gap-4">
              <div>
                <div className="text-[9px]" style={{ color: "#ef4444" }}>Low</div>
                <div className="text-sm font-bold tabular-nums" style={{ color: "var(--text-primary)" }}>
                  ${Number(summary.priceTargets.low).toLocaleString()}
                </div>
              </div>
              <div>
                <div className="text-[9px]" style={{ color: "var(--accent)" }}>Mid</div>
                <div className="text-lg font-black tabular-nums" style={{ color: "var(--text-primary)" }}>
                  ${Number(summary.priceTargets.mid).toLocaleString()}
                </div>
              </div>
              <div>
                <div className="text-[9px]" style={{ color: "#22c55e" }}>High</div>
                <div className="text-sm font-bold tabular-nums" style={{ color: "var(--text-primary)" }}>
                  ${Number(summary.priceTargets.high).toLocaleString()}
                </div>
              </div>
            </div>
          </Card>
        )}
      </div>
      <Card title="Intelligence Briefing (Stage 1.5)" accent>
        {brief?.executiveSummary ? (
          <>
            <p className="text-[11px] leading-relaxed" style={{ color: "var(--text-secondary)" }}>
              {brief.executiveSummary}
            </p>
            {brief.sentimentReading && (
              <div className="mt-2 text-[10px]">
                <span style={{ color: "var(--text-muted)" }}>Market sentiment from research: </span>
                <span className="font-bold" style={{ color: dirColor }}>{brief.sentimentReading}</span>
              </div>
            )}
          </>
        ) : (
          <p className="text-[10px] italic" style={{ color: "var(--text-muted)" }}>
            No intelligence briefing available. Check backend logs for Stage 1.5 errors (web search or LLM synthesis may have failed).
          </p>
        )}
      </Card>
      <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
        <Card title="Bull Case (Research)">
          {brief?.bullCase && brief.bullCase.length > 0 ? (
            <ul className="space-y-1.5">
              {brief.bullCase.map((b, i) => (
                <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                  <span style={{ color: "#22c55e" }}>▲</span>
                  <span>{b}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-[10px] italic" style={{ color: "var(--text-muted)" }}>No bull case identified in research.</p>
          )}
        </Card>
        <Card title="Bear Case (Research)">
          {brief?.bearCase && brief.bearCase.length > 0 ? (
            <ul className="space-y-1.5">
              {brief.bearCase.map((b, i) => (
                <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                  <span style={{ color: "#ef4444" }}>▼</span>
                  <span>{b}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-[10px] italic" style={{ color: "var(--text-muted)" }}>No bear case identified in research.</p>
          )}
        </Card>
      </div>
      {brief?.keyEvents && brief.keyEvents.length > 0 && (
        <Card title="Upcoming Events">
          <ul className="space-y-1.5">
            {brief.keyEvents.map((e, i) => (
              <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                <span style={{ color: "#f59e0b" }}>!</span>
                <span>{e}</span>
              </li>
            ))}
          </ul>
        </Card>
      )}
      <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
        {summary.keyArguments && summary.keyArguments.length > 0 && (
          <Card title="Key Arguments (Debate)">
            <ul className="space-y-1.5">
              {summary.keyArguments.map((arg, i) => (
                <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                  <span style={{ color: "#22c55e" }}>+</span>
                  <span>{arg}</span>
                </li>
              ))}
            </ul>
          </Card>
        )}

        {summary.dissentingViews && summary.dissentingViews.length > 0 && (
          <Card title="Dissenting Views">
            <ul className="space-y-1.5">
              {summary.dissentingViews.map((v, i) => (
                <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                  <span style={{ color: "#ef4444" }}>-</span>
                  <span>{v}</span>
                </li>
              ))}
            </ul>
          </Card>
        )}
      </div>
      <Card title={`Cross-Examination (Stage 4) — ${crossExam.length} agents`} accent>
        {crossExam.length > 0 ? (
          <div className="space-y-2">
            {crossExam.map((c, i) => {
              const changeColor =
                c.convictionChange === "reversed" ? "#ef4444"
                : c.convictionChange === "weakened" ? "#f59e0b"
                : c.convictionChange === "strengthened" ? "#22c55e"
                : "var(--text-muted)";
              return (
                <div key={i} className="rounded p-2" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-[11px] font-bold" style={{ color: "var(--text-primary)" }}>{c.entityName}</span>
                    <span className="text-[9px]" style={{ color: "var(--accent)" }}>{c.entityRole}</span>
                    <span className="ml-auto rounded px-1.5 py-0.5 text-[8px] font-bold uppercase" style={{ background: `${changeColor}22`, color: changeColor }}>
                      {c.convictionChange}
                    </span>
                  </div>
                  {c.question && (
                    <div className="mt-1 text-[9px] italic" style={{ color: "var(--text-muted)" }}>
                      Q: {c.question.slice(0, 200)}
                    </div>
                  )}
                  <div className="mt-1 text-[10px] leading-relaxed" style={{ color: "var(--text-secondary)" }}>
                    {c.response || "(no response)"}
                  </div>
                </div>
              );
            })}
          </div>
        ) : (
          <p className="text-[10px] italic" style={{ color: "var(--text-muted)" }}>
            No cross-examination performed. This runs automatically when agents have divergent views — check if debate completed fully.
          </p>
        )}
      </Card>
      {convictionShifts.length > 0 && (
        <Card title="Conviction Shifts During Debate">
          <ul className="space-y-1.5">
            {convictionShifts.map((s, i) => (
              <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                <span style={{ color: "var(--accent)" }}>→</span>
                <span>{s}</span>
              </li>
            ))}
          </ul>
        </Card>
      )}
      {summary.riskFactors && summary.riskFactors.length > 0 && (
        <Card title="Risk Factors">
          <ul className="space-y-1.5">
            {summary.riskFactors.map((r, i) => (
              <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                <span style={{ color: "#f59e0b" }}>⚠</span>
                <span>{r}</span>
              </li>
            ))}
          </ul>
        </Card>
      )}
      {brief?.dataPoints && brief.dataPoints.length > 0 && (
        <Card title="Key Data Points">
          <ul className="space-y-1 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
            {brief.dataPoints.map((d, i) => (
              <li key={i} className="font-mono">• {d}</li>
            ))}
          </ul>
        </Card>
      )}
      {Boolean(rec.action) && (
        <Card title="Trade Recommendation" accent>
          <div className="mt-1">
            <span className="rounded px-2 py-1 text-[11px] font-bold uppercase" style={{ background: `${dirColor}22`, color: dirColor }}>
              {String(rec.action)}
            </span>
          </div>
          <div className="mt-2 grid grid-cols-2 gap-x-4 gap-y-1 text-[10px]">
            {rec.entry != null && (
              <div>
                <span style={{ color: "var(--text-muted)" }}>Entry: </span>
                <span style={{ color: "var(--text-primary)" }}>${Number(rec.entry).toLocaleString()}</span>
              </div>
            )}
            {rec.stop != null && (
              <div>
                <span style={{ color: "var(--text-muted)" }}>Stop: </span>
                <span style={{ color: "#ef4444" }}>${Number(rec.stop).toLocaleString()}</span>
              </div>
            )}
            {rec.target != null && (
              <div>
                <span style={{ color: "var(--text-muted)" }}>Target: </span>
                <span style={{ color: "#22c55e" }}>${Number(rec.target).toLocaleString()}</span>
              </div>
            )}
            {rec.position_size_pct != null && (
              <div>
                <span style={{ color: "var(--text-muted)" }}>Size: </span>
                <span style={{ color: "var(--text-primary)" }}>{String(rec.position_size_pct)}%</span>
              </div>
            )}
          </div>
        </Card>
      )}
      {brief?.rawFindings && (
        <details className="rounded-lg" style={{ background: "var(--surface-2)", border: "1px solid var(--border)" }}>
          <summary className="cursor-pointer p-3 text-[9px] font-bold uppercase tracking-wider" style={{ color: "var(--text-muted)" }}>
            Raw Research Feeds (click to expand)
          </summary>
          <div className="p-3 pt-0 space-y-2 text-[9px] leading-relaxed" style={{ color: "var(--text-secondary)" }}>
            {brief.rawFindings.recentNews && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Recent News</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.recentNews.slice(0, 1500)}</pre>
              </div>
            )}
            {brief.rawFindings.technicalIndicators && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Technical Indicators</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.technicalIndicators}</pre>
              </div>
            )}
            {brief.rawFindings.keyLevels && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Key Price Levels</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.keyLevels}</pre>
              </div>
            )}
            {brief.rawFindings.marketAnalysis && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Market Analysis</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.marketAnalysis.slice(0, 1500)}</pre>
              </div>
            )}
            {brief.rawFindings.regulatory && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Regulatory</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.regulatory.slice(0, 1000)}</pre>
              </div>
            )}
          </div>
        </details>
      )}
    </div>
  );
}

function Card({ title, accent, children }: { title: string; accent?: boolean; children: React.ReactNode }) {
  return (
    <div
      className="rounded-lg p-4"
      style={{
        background: "var(--surface-2)",
        border: `1px solid ${accent ? "rgba(255, 107, 0, 0.3)" : "var(--border)"}`,
      }}
    >
      <div className="text-[9px] font-bold uppercase tracking-wider mb-2" style={{ color: accent ? "var(--accent)" : "var(--text-muted)" }}>
        {title}
      </div>
      {children}
    </div>
  );
}

function ConvergenceChart({ timeline }: { timeline: Array<{ round: number; sentiment: number }> }) {
  if (timeline.length === 0) return null;
  const width = 400;
  const height = 80;
  const padding = 10;
  const minSent = -1;
  const maxSent = 1;
  const xStep = (width - padding * 2) / Math.max(1, timeline.length - 1);
  const points = timeline.map((p, i) => {
    const x = padding + i * xStep;
    const y = height - padding - ((p.sentiment - minSent) / (maxSent - minSent)) * (height - padding * 2);
    return `${x},${y}`;
  }).join(" ");
  const zeroY = height - padding - ((0 - minSent) / (maxSent - minSent)) * (height - padding * 2);
  return (
    <div className="overflow-x-auto">
      <svg width={width} height={height} className="block" style={{ minWidth: width }}>
        {/* Zero line */}
        <line x1={padding} y1={zeroY} x2={width - padding} y2={zeroY} stroke="var(--border)" strokeDasharray="2 2" />
        {/* Sentiment line */}
        <polyline points={points} fill="none" stroke="var(--accent)" strokeWidth={2} />
        {/* Points */}
        {timeline.map((p, i) => {
          const x = padding + i * xStep;
          const y = height - padding - ((p.sentiment - minSent) / (maxSent - minSent)) * (height - padding * 2);
          const color = p.sentiment > 0.2 ? "#22c55e" : p.sentiment < -0.2 ? "#ef4444" : "var(--text-muted)";
          return <circle key={i} cx={x} cy={y} r={3} fill={color} />;
        })}
        {/* Y-axis labels */}
        <text x={2} y={padding + 4} fontSize={8} fill="var(--text-muted)">+1</text>
        <text x={2} y={zeroY + 3} fontSize={8} fill="var(--text-muted)">0</text>
        <text x={2} y={height - 2} fontSize={8} fill="var(--text-muted)">-1</text>
      </svg>
      <div className="mt-1 text-[9px]" style={{ color: "var(--text-muted)" }}>
        Round {timeline[0]?.round} → Round {timeline[timeline.length - 1]?.round} · {timeline.length} data points
      </div>
    </div>
  );
}

function DataStatus({ label, has, count }: { label: string; has: boolean; count?: number }) {
  return (
    <div className="flex items-center gap-1.5">
      <span style={{ color: has ? "#22c55e" : "var(--text-muted)" }}>
        {has ? "✓" : "○"}
      </span>
      <span style={{ color: has ? "var(--text-secondary)" : "var(--text-muted)", opacity: has ? 1 : 0.6 }}>
        {label}
      </span>
      {has && count !== undefined && count > 0 && (
        <span className="ml-auto font-mono text-[9px]" style={{ color: "var(--accent)" }}>
          {count}
        </span>
      )}
    </div>
  );
}
