"use client";

import { useState, useRef } from "react";
import { useStore } from "@/store/useStore";

/**
 * Full pipeline dashboard: consensus, price targets, key arguments,
 * intelligence briefing, cross-examination results, and trade setup.
 * Shows ALL data generated by the 5-stage pipeline.
 */
export function RunStatsTab() {
  const debate = useStore((s) => s.currentDebate);
  const summary = debate?.summary;

  if (!summary) {
    return (
      <div className="flex h-full items-center justify-center text-xs" style={{ color: "var(--text-muted)" }}>
        Run a swarm debate to see run statistics
      </div>
    );
  }

  const dirColor =
    summary.consensusDirection === "BULLISH" ? "#22c55e"
    : summary.consensusDirection === "BEARISH" ? "#ef4444"
    : "#ff6b00";

  const rec = (summary.recommendation || {}) as Record<string, unknown>;
  const brief = debate.intelBriefing;
  const crossExam = (debate.crossExamResults || []) as import("@/types").CrossExamResult[];
  const convictionShifts: string[] = summary.convictionShifts || [];
  const marketContext = debate.marketContext;
  const dataFeeds = debate.dataFeeds || {};
  const timeline = debate.convergenceTimeline || [];
  const agentResearch = debate.agentResearch || {};
  const totalResearchQueries = Object.values(agentResearch).reduce((acc, arr) => acc + arr.length, 0);

  const [exporting, setExporting] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  const handleExportPDF = async () => {
    if (!reportRef.current || exporting) return;
    setExporting(true);
    try {
      // Lazy-load to keep initial bundle small
      const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
        import("jspdf"),
        import("html2canvas"),
      ]);

      const element = reportRef.current;

      // Expand all <details> elements so nothing is hidden in the PDF
      const detailsEls = Array.from(element.querySelectorAll("details"));
      const originalStates = detailsEls.map((d) => d.open);
      detailsEls.forEach((d) => { d.open = true; });

      // Force the container and ALL its scrollable ancestors to show full
      // content. html2canvas only captures visible content — with overflow:auto
      // + fixed height, it only gets the viewport. We temporarily override
      // these styles, clone-less via direct mutation, then restore.
      const restoreFns: Array<() => void> = [];
      let el: HTMLElement | null = element;
      while (el && el !== document.body) {
        const styles: Partial<CSSStyleDeclaration> = {
          height: el.style.height,
          maxHeight: el.style.maxHeight,
          overflow: el.style.overflow,
          overflowY: el.style.overflowY,
          overflowX: el.style.overflowX,
        };
        const elRef = el;
        restoreFns.push(() => {
          elRef.style.height = styles.height || "";
          elRef.style.maxHeight = styles.maxHeight || "";
          elRef.style.overflow = styles.overflow || "";
          elRef.style.overflowY = styles.overflowY || "";
          elRef.style.overflowX = styles.overflowX || "";
        });
        el.style.height = "auto";
        el.style.maxHeight = "none";
        el.style.overflow = "visible";
        el.style.overflowY = "visible";
        el.style.overflowX = "visible";
        el = el.parentElement;
      }

      // Let the DOM reflow so we get the full scroll height
      await new Promise((r) => setTimeout(r, 150));

      // Now capture — html2canvas will see the entire report
      const canvas = await html2canvas(element, {
        scale: 2,
        backgroundColor: "#0d0d10",
        useCORS: true,
        allowTaint: true,
        logging: false,
        scrollX: 0,
        scrollY: 0,
        windowWidth: element.scrollWidth,
        windowHeight: element.scrollHeight,
        width: element.scrollWidth,
        height: element.scrollHeight,
      });

      // Restore original styles + details states
      restoreFns.forEach((fn) => fn());
      detailsEls.forEach((d, i) => { d.open = originalStates[i]; });

      // Build multi-page PDF: slice the canvas into A4-sized chunks
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const margin = 5;
      const contentWidth = pdfWidth - margin * 2;
      const contentHeight = pdfHeight - margin * 2;

      // Scale factor from canvas px → mm on page
      const scale = contentWidth / canvas.width;

      // How much canvas height fits on one page (in canvas px)?
      const pagePxHeight = contentHeight / scale;

      let offsetY = 0;
      let pageNum = 0;
      while (offsetY < canvas.height) {
        if (pageNum > 0) pdf.addPage();
        const sliceHeight = Math.min(pagePxHeight, canvas.height - offsetY);
        // Create a temporary canvas for this slice
        const sliceCanvas = document.createElement("canvas");
        sliceCanvas.width = canvas.width;
        sliceCanvas.height = sliceHeight;
        const ctx = sliceCanvas.getContext("2d");
        if (ctx) {
          // Fill with dark background so the slice is consistent
          ctx.fillStyle = "#0d0d10";
          ctx.fillRect(0, 0, sliceCanvas.width, sliceCanvas.height);
          ctx.drawImage(canvas, 0, offsetY, canvas.width, sliceHeight, 0, 0, canvas.width, sliceHeight);
        }
        const sliceData = sliceCanvas.toDataURL("image/png");
        pdf.addImage(sliceData, "PNG", margin, margin, contentWidth, sliceHeight * scale);
        offsetY += sliceHeight;
        pageNum++;
      }

      const assetName = (debate.assetName || debate.symbol || "asset").replace(/[^a-zA-Z0-9_-]/g, "_");
      const date = new Date().toISOString().slice(0, 10);
      pdf.save(`swarm_debate_${assetName}_${date}.pdf`);
    } catch (err) {
      console.error("PDF export failed:", err);
      alert("PDF export failed: " + (err instanceof Error ? err.message : String(err)));
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="h-full overflow-y-auto p-3 space-y-3" ref={reportRef}>
      {/* Export header */}
      <div className="flex items-center gap-2 -mb-1">
        <div className="text-[9px] font-bold uppercase tracking-wider" style={{ color: "var(--text-muted)" }}>
          {debate.assetName} · {debate.entities.length} personas · {debate.totalRounds} rounds
        </div>
        <button
          onClick={handleExportPDF}
          disabled={exporting}
          className="ml-auto flex items-center gap-1.5 rounded px-2.5 py-1 text-[10px] font-semibold transition-colors disabled:opacity-40"
          style={{
            background: exporting ? "var(--surface-2)" : "rgba(255, 107, 0, 0.12)",
            color: "var(--accent)",
            border: "1px solid rgba(255, 107, 0, 0.3)",
          }}
          title="Export full report as PDF"
          data-html2canvas-ignore="true"
        >
          <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          {exporting ? "Generating..." : "Export PDF"}
        </button>
      </div>

      <div className="rounded-lg p-3" style={{ background: "var(--surface-2)", border: "1px solid var(--border)" }}>
        <div className="text-[9px] font-bold uppercase tracking-wider mb-2" style={{ color: "var(--text-muted)" }}>
          Pipeline Data Available
        </div>
        <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-[10px] sm:grid-cols-3 lg:grid-cols-4">
          <DataStatus label="Intelligence Briefing" has={!!brief?.executiveSummary} />
          <DataStatus label="Bull Case" has={(brief?.bullCase?.length ?? 0) > 0} count={brief?.bullCase?.length} />
          <DataStatus label="Bear Case" has={(brief?.bearCase?.length ?? 0) > 0} count={brief?.bearCase?.length} />
          <DataStatus label="Key Events" has={(brief?.keyEvents?.length ?? 0) > 0} count={brief?.keyEvents?.length} />
          <DataStatus label="Data Points" has={(brief?.dataPoints?.length ?? 0) > 0} count={brief?.dataPoints?.length} />
          <DataStatus label="Cross-Exams" has={crossExam.length > 0} count={crossExam.length} />
          <DataStatus label="Conviction Shifts" has={convictionShifts.length > 0} count={convictionShifts.length} />
          <DataStatus label="Trade Recommendation" has={!!rec.action} />
          <DataStatus label="Raw News" has={!!brief?.rawFindings?.recentNews} />
          <DataStatus label="Tech Indicators" has={!!brief?.rawFindings?.technicalIndicators} />
          <DataStatus label="Regulatory" has={!!brief?.rawFindings?.regulatory} />
          <DataStatus label="Market Analysis" has={!!brief?.rawFindings?.marketAnalysis} />
          <DataStatus label="Market Context" has={!!marketContext?.marketRegime} />
          <DataStatus label="Technical Signals" has={(marketContext?.technicalSignals?.length ?? 0) > 0} count={marketContext?.technicalSignals?.length} />
          <DataStatus label="Key Themes" has={(marketContext?.keyThemes?.length ?? 0) > 0} count={marketContext?.keyThemes?.length} />
          <DataStatus label="Risk Events" has={(marketContext?.riskEvents?.length ?? 0) > 0} count={marketContext?.riskEvents?.length} />
          <DataStatus label="Data Feeds" has={Object.keys(dataFeeds).length > 0} count={Object.keys(dataFeeds).length} />
          <DataStatus label="Agent Research" has={totalResearchQueries > 0} count={totalResearchQueries} />
          <DataStatus label="Convergence Timeline" has={timeline.length > 0} count={timeline.length} />
        </div>
      </div>

      {/* Market Context (Stage 1 output — previously hidden) */}
      {marketContext && (
        <Card title="Market Context (Stage 1)" accent>
          <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
            {marketContext.marketRegime && (
              <div>
                <div className="text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: "var(--text-muted)" }}>Market Regime</div>
                <div className="text-[11px] font-bold" style={{ color: dirColor }}>{marketContext.marketRegime}</div>
              </div>
            )}
            {marketContext.volumeAnalysis && (
              <div>
                <div className="text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: "var(--text-muted)" }}>Volume Analysis</div>
                <div className="text-[10px]" style={{ color: "var(--text-secondary)" }}>{marketContext.volumeAnalysis}</div>
              </div>
            )}
            {marketContext.keyPriceLevels && (
              <div className="lg:col-span-2">
                <div className="text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: "var(--text-muted)" }}>Key Price Levels</div>
                <div className="flex gap-3 text-[10px]">
                  {marketContext.keyPriceLevels.strongResistance && marketContext.keyPriceLevels.strongResistance.length > 0 && (
                    <span><span style={{ color: "#ef4444" }}>Resistance:</span> {marketContext.keyPriceLevels.strongResistance.map(n => `$${Number(n).toLocaleString()}`).join(", ")}</span>
                  )}
                  {marketContext.keyPriceLevels.strongSupport && marketContext.keyPriceLevels.strongSupport.length > 0 && (
                    <span><span style={{ color: "#22c55e" }}>Support:</span> {marketContext.keyPriceLevels.strongSupport.map(n => `$${Number(n).toLocaleString()}`).join(", ")}</span>
                  )}
                </div>
              </div>
            )}
            {marketContext.technicalSignals && marketContext.technicalSignals.length > 0 && (
              <div>
                <div className="text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: "var(--text-muted)" }}>Technical Signals</div>
                <ul className="space-y-0.5 text-[10px]" style={{ color: "var(--text-secondary)" }}>
                  {marketContext.technicalSignals.map((s, i) => <li key={i}>• {s}</li>)}
                </ul>
              </div>
            )}
            {marketContext.keyThemes && marketContext.keyThemes.length > 0 && (
              <div>
                <div className="text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: "var(--text-muted)" }}>Key Themes</div>
                <div className="flex flex-wrap gap-1">
                  {marketContext.keyThemes.map((t, i) => (
                    <span key={i} className="rounded px-1.5 py-0.5 text-[9px]" style={{ background: "var(--surface)", color: "var(--text-secondary)", border: "1px solid var(--border)" }}>{t}</span>
                  ))}
                </div>
              </div>
            )}
            {marketContext.riskEvents && marketContext.riskEvents.length > 0 && (
              <div className="lg:col-span-2">
                <div className="text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: "var(--text-muted)" }}>Risk Events</div>
                <ul className="space-y-0.5 text-[10px]" style={{ color: "var(--text-secondary)" }}>
                  {marketContext.riskEvents.map((r, i) => <li key={i} className="flex gap-1"><span style={{ color: "#f59e0b" }}>!</span>{r}</li>)}
                </ul>
              </div>
            )}
          </div>
        </Card>
      )}

      {/* Convergence Timeline (sentiment per round) */}
      {timeline.length > 0 && (
        <Card title={`Sentiment Convergence (${timeline.length} rounds)`}>
          <ConvergenceChart timeline={timeline} />
        </Card>
      )}

      {/* Agent Research Summary */}
      {totalResearchQueries > 0 && (
        <Card title={`Iterative Research (${totalResearchQueries} queries across ${Object.keys(agentResearch).length} agents)`} accent>
          <div className="text-[10px]" style={{ color: "var(--text-secondary)" }}>
            Agents did deep research before the debate. Click any persona card in the Personalities tab to see each agent's full research trail with query reasoning and findings.
          </div>
          <div className="mt-2 text-[9px]" style={{ color: "var(--text-muted)" }}>
            Average per agent: {(totalResearchQueries / Object.keys(agentResearch).length).toFixed(1)} queries
          </div>
        </Card>
      )}
      <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
        <Card title="Consensus">
          <div className="flex items-baseline gap-3">
            <span className="rounded-md px-3 py-1 text-sm font-black uppercase tracking-wide" style={{ background: `${dirColor}22`, color: dirColor }}>
              {summary.consensusDirection}
            </span>
            <span className="text-2xl font-bold tabular-nums" style={{ color: "var(--text-primary)" }}>
              {summary.confidence.toFixed(0)}%
            </span>
          </div>
          <div className="mt-1 text-[10px]" style={{ color: "var(--text-muted)" }}>
            {debate.entities.length} personas, {debate.totalRounds} rounds, {debate.thread.length} messages
          </div>
        </Card>

        {summary.priceTargets && (
          <Card title="Price Targets">
            <div className="flex items-end gap-4">
              <div>
                <div className="text-[9px]" style={{ color: "#ef4444" }}>Low</div>
                <div className="text-sm font-bold tabular-nums" style={{ color: "var(--text-primary)" }}>
                  ${Number(summary.priceTargets.low).toLocaleString()}
                </div>
              </div>
              <div>
                <div className="text-[9px]" style={{ color: "var(--accent)" }}>Mid</div>
                <div className="text-lg font-black tabular-nums" style={{ color: "var(--text-primary)" }}>
                  ${Number(summary.priceTargets.mid).toLocaleString()}
                </div>
              </div>
              <div>
                <div className="text-[9px]" style={{ color: "#22c55e" }}>High</div>
                <div className="text-sm font-bold tabular-nums" style={{ color: "var(--text-primary)" }}>
                  ${Number(summary.priceTargets.high).toLocaleString()}
                </div>
              </div>
            </div>
          </Card>
        )}
      </div>
      <Card title="Intelligence Briefing (Stage 1.5)" accent>
        {brief?.executiveSummary ? (
          <>
            <p className="text-[11px] leading-relaxed" style={{ color: "var(--text-secondary)" }}>
              {brief.executiveSummary}
            </p>
            {brief.sentimentReading && (
              <div className="mt-2 text-[10px]">
                <span style={{ color: "var(--text-muted)" }}>Market sentiment from research: </span>
                <span className="font-bold" style={{ color: dirColor }}>{brief.sentimentReading}</span>
              </div>
            )}
          </>
        ) : (
          <p className="text-[10px] italic" style={{ color: "var(--text-muted)" }}>
            No intelligence briefing available. Check backend logs for Stage 1.5 errors (web search or LLM synthesis may have failed).
          </p>
        )}
      </Card>
      <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
        <Card title="Bull Case (Research)">
          {brief?.bullCase && brief.bullCase.length > 0 ? (
            <ul className="space-y-1.5">
              {brief.bullCase.map((b, i) => (
                <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                  <span style={{ color: "#22c55e" }}>▲</span>
                  <span>{b}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-[10px] italic" style={{ color: "var(--text-muted)" }}>No bull case identified in research.</p>
          )}
        </Card>
        <Card title="Bear Case (Research)">
          {brief?.bearCase && brief.bearCase.length > 0 ? (
            <ul className="space-y-1.5">
              {brief.bearCase.map((b, i) => (
                <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                  <span style={{ color: "#ef4444" }}>▼</span>
                  <span>{b}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-[10px] italic" style={{ color: "var(--text-muted)" }}>No bear case identified in research.</p>
          )}
        </Card>
      </div>
      {brief?.keyEvents && brief.keyEvents.length > 0 && (
        <Card title="Upcoming Events">
          <ul className="space-y-1.5">
            {brief.keyEvents.map((e, i) => (
              <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                <span style={{ color: "#f59e0b" }}>!</span>
                <span>{e}</span>
              </li>
            ))}
          </ul>
        </Card>
      )}
      <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
        {summary.keyArguments && summary.keyArguments.length > 0 && (
          <Card title="Key Arguments (Debate)">
            <ul className="space-y-1.5">
              {summary.keyArguments.map((arg, i) => (
                <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                  <span style={{ color: "#22c55e" }}>+</span>
                  <span>{arg}</span>
                </li>
              ))}
            </ul>
          </Card>
        )}

        {summary.dissentingViews && summary.dissentingViews.length > 0 && (
          <Card title="Dissenting Views">
            <ul className="space-y-1.5">
              {summary.dissentingViews.map((v, i) => (
                <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                  <span style={{ color: "#ef4444" }}>-</span>
                  <span>{v}</span>
                </li>
              ))}
            </ul>
          </Card>
        )}
      </div>
      <Card title={`Cross-Examination (Stage 4) — ${crossExam.length} agents`} accent>
        {crossExam.length > 0 ? (
          <div className="space-y-2">
            {crossExam.map((c, i) => {
              const changeColor =
                c.convictionChange === "reversed" ? "#ef4444"
                : c.convictionChange === "weakened" ? "#f59e0b"
                : c.convictionChange === "strengthened" ? "#22c55e"
                : "var(--text-muted)";
              return (
                <div key={i} className="rounded p-2" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-[11px] font-bold" style={{ color: "var(--text-primary)" }}>{c.entityName}</span>
                    <span className="text-[9px]" style={{ color: "var(--accent)" }}>{c.entityRole}</span>
                    <span className="ml-auto rounded px-1.5 py-0.5 text-[8px] font-bold uppercase" style={{ background: `${changeColor}22`, color: changeColor }}>
                      {c.convictionChange}
                    </span>
                  </div>
                  {c.question && (
                    <div className="mt-1 text-[9px] italic" style={{ color: "var(--text-muted)" }}>
                      Q: {c.question.slice(0, 200)}
                    </div>
                  )}
                  <div className="mt-1 text-[10px] leading-relaxed" style={{ color: "var(--text-secondary)" }}>
                    {c.response || "(no response)"}
                  </div>
                </div>
              );
            })}
          </div>
        ) : (
          <p className="text-[10px] italic" style={{ color: "var(--text-muted)" }}>
            No cross-examination performed. This runs automatically when agents have divergent views — check if debate completed fully.
          </p>
        )}
      </Card>
      {convictionShifts.length > 0 && (
        <Card title="Conviction Shifts During Debate">
          <ul className="space-y-1.5">
            {convictionShifts.map((s, i) => (
              <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                <span style={{ color: "var(--accent)" }}>→</span>
                <span>{s}</span>
              </li>
            ))}
          </ul>
        </Card>
      )}
      {summary.riskFactors && summary.riskFactors.length > 0 && (
        <Card title="Risk Factors">
          <ul className="space-y-1.5">
            {summary.riskFactors.map((r, i) => (
              <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                <span style={{ color: "#f59e0b" }}>⚠</span>
                <span>{r}</span>
              </li>
            ))}
          </ul>
        </Card>
      )}
      {brief?.dataPoints && brief.dataPoints.length > 0 && (
        <Card title="Key Data Points">
          <ul className="space-y-1 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
            {brief.dataPoints.map((d, i) => (
              <li key={i} className="font-mono">• {d}</li>
            ))}
          </ul>
        </Card>
      )}
      {Boolean(rec.action) && (
        <Card title="Trade Recommendation" accent>
          <div className="mt-1">
            <span className="rounded px-2 py-1 text-[11px] font-bold uppercase" style={{ background: `${dirColor}22`, color: dirColor }}>
              {String(rec.action)}
            </span>
          </div>
          <div className="mt-2 grid grid-cols-2 gap-x-4 gap-y-1 text-[10px]">
            {rec.entry != null && (
              <div>
                <span style={{ color: "var(--text-muted)" }}>Entry: </span>
                <span style={{ color: "var(--text-primary)" }}>${Number(rec.entry).toLocaleString()}</span>
              </div>
            )}
            {rec.stop != null && (
              <div>
                <span style={{ color: "var(--text-muted)" }}>Stop: </span>
                <span style={{ color: "#ef4444" }}>${Number(rec.stop).toLocaleString()}</span>
              </div>
            )}
            {rec.target != null && (
              <div>
                <span style={{ color: "var(--text-muted)" }}>Target: </span>
                <span style={{ color: "#22c55e" }}>${Number(rec.target).toLocaleString()}</span>
              </div>
            )}
            {rec.position_size_pct != null && (
              <div>
                <span style={{ color: "var(--text-muted)" }}>Size: </span>
                <span style={{ color: "var(--text-primary)" }}>{String(rec.position_size_pct)}%</span>
              </div>
            )}
          </div>
        </Card>
      )}
      {brief?.rawFindings && (
        <details className="rounded-lg" style={{ background: "var(--surface-2)", border: "1px solid var(--border)" }}>
          <summary className="cursor-pointer p-3 text-[9px] font-bold uppercase tracking-wider" style={{ color: "var(--text-muted)" }}>
            Raw Research Feeds (click to expand)
          </summary>
          <div className="p-3 pt-0 space-y-2 text-[9px] leading-relaxed" style={{ color: "var(--text-secondary)" }}>
            {brief.rawFindings.recentNews && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Recent News</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.recentNews.slice(0, 1500)}</pre>
              </div>
            )}
            {brief.rawFindings.technicalIndicators && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Technical Indicators</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.technicalIndicators}</pre>
              </div>
            )}
            {brief.rawFindings.keyLevels && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Key Price Levels</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.keyLevels}</pre>
              </div>
            )}
            {brief.rawFindings.marketAnalysis && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Market Analysis</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.marketAnalysis.slice(0, 1500)}</pre>
              </div>
            )}
            {brief.rawFindings.regulatory && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Regulatory</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.regulatory.slice(0, 1000)}</pre>
              </div>
            )}
          </div>
        </details>
      )}
    </div>
  );
}

function Card({ title, accent, children }: { title: string; accent?: boolean; children: React.ReactNode }) {
  return (
    <div
      className="rounded-lg p-4"
      style={{
        background: "var(--surface-2)",
        border: `1px solid ${accent ? "rgba(255, 107, 0, 0.3)" : "var(--border)"}`,
      }}
    >
      <div className="text-[9px] font-bold uppercase tracking-wider mb-2" style={{ color: accent ? "var(--accent)" : "var(--text-muted)" }}>
        {title}
      </div>
      {children}
    </div>
  );
}

function ConvergenceChart({ timeline }: { timeline: Array<{ round: number; sentiment: number }> }) {
  if (timeline.length === 0) return null;
  const width = 400;
  const height = 80;
  const padding = 10;
  const minSent = -1;
  const maxSent = 1;
  const xStep = (width - padding * 2) / Math.max(1, timeline.length - 1);
  const points = timeline.map((p, i) => {
    const x = padding + i * xStep;
    const y = height - padding - ((p.sentiment - minSent) / (maxSent - minSent)) * (height - padding * 2);
    return `${x},${y}`;
  }).join(" ");
  const zeroY = height - padding - ((0 - minSent) / (maxSent - minSent)) * (height - padding * 2);
  return (
    <div className="overflow-x-auto">
      <svg width={width} height={height} className="block" style={{ minWidth: width }}>
        {/* Zero line */}
        <line x1={padding} y1={zeroY} x2={width - padding} y2={zeroY} stroke="var(--border)" strokeDasharray="2 2" />
        {/* Sentiment line */}
        <polyline points={points} fill="none" stroke="var(--accent)" strokeWidth={2} />
        {/* Points */}
        {timeline.map((p, i) => {
          const x = padding + i * xStep;
          const y = height - padding - ((p.sentiment - minSent) / (maxSent - minSent)) * (height - padding * 2);
          const color = p.sentiment > 0.2 ? "#22c55e" : p.sentiment < -0.2 ? "#ef4444" : "var(--text-muted)";
          return <circle key={i} cx={x} cy={y} r={3} fill={color} />;
        })}
        {/* Y-axis labels */}
        <text x={2} y={padding + 4} fontSize={8} fill="var(--text-muted)">+1</text>
        <text x={2} y={zeroY + 3} fontSize={8} fill="var(--text-muted)">0</text>
        <text x={2} y={height - 2} fontSize={8} fill="var(--text-muted)">-1</text>
      </svg>
      <div className="mt-1 text-[9px]" style={{ color: "var(--text-muted)" }}>
        Round {timeline[0]?.round} → Round {timeline[timeline.length - 1]?.round} · {timeline.length} data points
      </div>
    </div>
  );
}

function DataStatus({ label, has, count }: { label: string; has: boolean; count?: number }) {
  return (
    <div className="flex items-center gap-1.5">
      <span style={{ color: has ? "#22c55e" : "var(--text-muted)" }}>
        {has ? "✓" : "○"}
      </span>
      <span style={{ color: has ? "var(--text-secondary)" : "var(--text-muted)", opacity: has ? 1 : 0.6 }}>
        {label}
      </span>
      {has && count !== undefined && count > 0 && (
        <span className="ml-auto font-mono text-[9px]" style={{ color: "var(--accent)" }}>
          {count}
        </span>
      )}
    </div>
  );
}
