"use client";

import { useStore } from "@/store/useStore";

/**
 * Full pipeline dashboard: consensus, price targets, key arguments,
 * intelligence briefing, cross-examination results, and trade setup.
 * Shows ALL data generated by the 5-stage pipeline.
 */
export function RunStatsTab() {
  const debate = useStore((s) => s.currentDebate);
  const summary = debate?.summary;

  if (!summary) {
    return (
      <div className="flex h-full items-center justify-center text-xs" style={{ color: "var(--text-muted)" }}>
        Run a swarm debate to see run statistics
      </div>
    );
  }

  const dirColor =
    summary.consensusDirection === "BULLISH" ? "#22c55e"
    : summary.consensusDirection === "BEARISH" ? "#ef4444"
    : "#ff6b00";

  const rec = (summary.recommendation || {}) as Record<string, unknown>;
  const brief = debate.intelBriefing;
  const crossExam = debate.crossExamResults || [];
  const convictionShifts = summary.convictionShifts || [];

  return (
    <div className="h-full overflow-y-auto p-3 space-y-3">
      {/* ── Top row: consensus + price targets ── */}
      <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
        <Card title="Consensus">
          <div className="flex items-baseline gap-3">
            <span className="rounded-md px-3 py-1 text-sm font-black uppercase tracking-wide" style={{ background: `${dirColor}22`, color: dirColor }}>
              {summary.consensusDirection}
            </span>
            <span className="text-2xl font-bold tabular-nums" style={{ color: "var(--text-primary)" }}>
              {summary.confidence.toFixed(0)}%
            </span>
          </div>
          <div className="mt-1 text-[10px]" style={{ color: "var(--text-muted)" }}>
            {debate.entities.length} personas, {debate.totalRounds} rounds, {debate.thread.length} messages
          </div>
        </Card>

        {summary.priceTargets && (
          <Card title="Price Targets">
            <div className="flex items-end gap-4">
              <div>
                <div className="text-[9px]" style={{ color: "#ef4444" }}>Low</div>
                <div className="text-sm font-bold tabular-nums" style={{ color: "var(--text-primary)" }}>
                  ${Number(summary.priceTargets.low).toLocaleString()}
                </div>
              </div>
              <div>
                <div className="text-[9px]" style={{ color: "var(--accent)" }}>Mid</div>
                <div className="text-lg font-black tabular-nums" style={{ color: "var(--text-primary)" }}>
                  ${Number(summary.priceTargets.mid).toLocaleString()}
                </div>
              </div>
              <div>
                <div className="text-[9px]" style={{ color: "#22c55e" }}>High</div>
                <div className="text-sm font-bold tabular-nums" style={{ color: "var(--text-primary)" }}>
                  ${Number(summary.priceTargets.high).toLocaleString()}
                </div>
              </div>
            </div>
          </Card>
        )}
      </div>

      {/* ── Intelligence Briefing (from Stage 1.5) ── */}
      {brief?.executiveSummary && (
        <Card title="Intelligence Briefing" accent>
          <p className="text-[11px] leading-relaxed" style={{ color: "var(--text-secondary)" }}>
            {brief.executiveSummary}
          </p>
          {brief.sentimentReading && (
            <div className="mt-2 text-[10px]">
              <span style={{ color: "var(--text-muted)" }}>Market sentiment from research: </span>
              <span className="font-bold" style={{ color: dirColor }}>{brief.sentimentReading}</span>
            </div>
          )}
        </Card>
      )}

      {/* ── Bull vs Bear case (from intel briefing) ── */}
      {((brief?.bullCase?.length ?? 0) > 0 || (brief?.bearCase?.length ?? 0) > 0) && (
        <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
          {brief?.bullCase && brief.bullCase.length > 0 && (
            <Card title="Bull Case (Research)">
              <ul className="space-y-1.5">
                {brief.bullCase.map((b, i) => (
                  <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                    <span style={{ color: "#22c55e" }}>▲</span>
                    <span>{b}</span>
                  </li>
                ))}
              </ul>
            </Card>
          )}
          {brief?.bearCase && brief.bearCase.length > 0 && (
            <Card title="Bear Case (Research)">
              <ul className="space-y-1.5">
                {brief.bearCase.map((b, i) => (
                  <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                    <span style={{ color: "#ef4444" }}>▼</span>
                    <span>{b}</span>
                  </li>
                ))}
              </ul>
            </Card>
          )}
        </div>
      )}

      {/* ── Key events from research ── */}
      {brief?.keyEvents && brief.keyEvents.length > 0 && (
        <Card title="Upcoming Events">
          <ul className="space-y-1.5">
            {brief.keyEvents.map((e, i) => (
              <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                <span style={{ color: "#f59e0b" }}>!</span>
                <span>{e}</span>
              </li>
            ))}
          </ul>
        </Card>
      )}

      {/* ── Debate consensus arguments ── */}
      <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
        {summary.keyArguments && summary.keyArguments.length > 0 && (
          <Card title="Key Arguments (Debate)">
            <ul className="space-y-1.5">
              {summary.keyArguments.map((arg, i) => (
                <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                  <span style={{ color: "#22c55e" }}>+</span>
                  <span>{arg}</span>
                </li>
              ))}
            </ul>
          </Card>
        )}

        {summary.dissentingViews && summary.dissentingViews.length > 0 && (
          <Card title="Dissenting Views">
            <ul className="space-y-1.5">
              {summary.dissentingViews.map((v, i) => (
                <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                  <span style={{ color: "#ef4444" }}>-</span>
                  <span>{v}</span>
                </li>
              ))}
            </ul>
          </Card>
        )}
      </div>

      {/* ── Cross-Examination Results ── */}
      {crossExam.length > 0 && (
        <Card title={`Cross-Examination (${crossExam.length} agents)`} accent>
          <div className="space-y-2">
            {crossExam.map((c, i) => {
              const changeColor =
                c.convictionChange === "reversed" ? "#ef4444"
                : c.convictionChange === "weakened" ? "#f59e0b"
                : c.convictionChange === "strengthened" ? "#22c55e"
                : "var(--text-muted)";
              return (
                <div key={i} className="rounded p-2" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-[11px] font-bold" style={{ color: "var(--text-primary)" }}>{c.entityName}</span>
                    <span className="text-[9px]" style={{ color: "var(--accent)" }}>{c.entityRole}</span>
                    <span className="ml-auto rounded px-1.5 py-0.5 text-[8px] font-bold uppercase" style={{ background: `${changeColor}22`, color: changeColor }}>
                      {c.convictionChange}
                    </span>
                  </div>
                  <div className="mt-1 text-[9px] italic" style={{ color: "var(--text-muted)" }}>
                    Q: {c.question.slice(0, 150)}
                  </div>
                  <div className="mt-1 text-[10px] leading-relaxed line-clamp-4" style={{ color: "var(--text-secondary)" }}>
                    {c.response}
                  </div>
                </div>
              );
            })}
          </div>
        </Card>
      )}

      {/* ── Conviction Shifts ── */}
      {convictionShifts.length > 0 && (
        <Card title="Conviction Shifts During Debate">
          <ul className="space-y-1.5">
            {convictionShifts.map((s, i) => (
              <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                <span style={{ color: "var(--accent)" }}>→</span>
                <span>{s}</span>
              </li>
            ))}
          </ul>
        </Card>
      )}

      {/* ── Risk Factors ── */}
      {summary.riskFactors && summary.riskFactors.length > 0 && (
        <Card title="Risk Factors">
          <ul className="space-y-1.5">
            {summary.riskFactors.map((r, i) => (
              <li key={i} className="flex gap-2 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
                <span style={{ color: "#f59e0b" }}>⚠</span>
                <span>{r}</span>
              </li>
            ))}
          </ul>
        </Card>
      )}

      {/* ── Data points cited ── */}
      {brief?.dataPoints && brief.dataPoints.length > 0 && (
        <Card title="Key Data Points">
          <ul className="space-y-1 text-[10px] leading-snug" style={{ color: "var(--text-secondary)" }}>
            {brief.dataPoints.map((d, i) => (
              <li key={i} className="font-mono">• {d}</li>
            ))}
          </ul>
        </Card>
      )}

      {/* ── Trade Recommendation ── */}
      {rec.action && (
        <Card title="Trade Recommendation" accent>
          <div className="mt-1">
            <span className="rounded px-2 py-1 text-[11px] font-bold uppercase" style={{ background: `${dirColor}22`, color: dirColor }}>
              {String(rec.action)}
            </span>
          </div>
          <div className="mt-2 grid grid-cols-2 gap-x-4 gap-y-1 text-[10px]">
            {rec.entry != null && (
              <div>
                <span style={{ color: "var(--text-muted)" }}>Entry: </span>
                <span style={{ color: "var(--text-primary)" }}>${Number(rec.entry).toLocaleString()}</span>
              </div>
            )}
            {rec.stop != null && (
              <div>
                <span style={{ color: "var(--text-muted)" }}>Stop: </span>
                <span style={{ color: "#ef4444" }}>${Number(rec.stop).toLocaleString()}</span>
              </div>
            )}
            {rec.target != null && (
              <div>
                <span style={{ color: "var(--text-muted)" }}>Target: </span>
                <span style={{ color: "#22c55e" }}>${Number(rec.target).toLocaleString()}</span>
              </div>
            )}
            {rec.position_size_pct != null && (
              <div>
                <span style={{ color: "var(--text-muted)" }}>Size: </span>
                <span style={{ color: "var(--text-primary)" }}>{String(rec.position_size_pct)}%</span>
              </div>
            )}
          </div>
        </Card>
      )}

      {/* ── Raw Research Feeds (collapsible) ── */}
      {brief?.rawFindings && (
        <details className="rounded-lg" style={{ background: "var(--surface-2)", border: "1px solid var(--border)" }}>
          <summary className="cursor-pointer p-3 text-[9px] font-bold uppercase tracking-wider" style={{ color: "var(--text-muted)" }}>
            Raw Research Feeds (click to expand)
          </summary>
          <div className="p-3 pt-0 space-y-2 text-[9px] leading-relaxed" style={{ color: "var(--text-secondary)" }}>
            {brief.rawFindings.recentNews && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Recent News</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.recentNews.slice(0, 1500)}</pre>
              </div>
            )}
            {brief.rawFindings.technicalIndicators && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Technical Indicators</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.technicalIndicators}</pre>
              </div>
            )}
            {brief.rawFindings.keyLevels && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Key Price Levels</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.keyLevels}</pre>
              </div>
            )}
            {brief.rawFindings.marketAnalysis && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Market Analysis</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.marketAnalysis.slice(0, 1500)}</pre>
              </div>
            )}
            {brief.rawFindings.regulatory && (
              <div>
                <div className="font-bold uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>Regulatory</div>
                <pre className="whitespace-pre-wrap font-mono text-[9px]">{brief.rawFindings.regulatory.slice(0, 1000)}</pre>
              </div>
            )}
          </div>
        </details>
      )}
    </div>
  );
}

function Card({ title, accent, children }: { title: string; accent?: boolean; children: React.ReactNode }) {
  return (
    <div
      className="rounded-lg p-4"
      style={{
        background: "var(--surface-2)",
        border: `1px solid ${accent ? "rgba(255, 107, 0, 0.3)" : "var(--border)"}`,
      }}
    >
      <div className="text-[9px] font-bold uppercase tracking-wider mb-2" style={{ color: accent ? "var(--accent)" : "var(--text-muted)" }}>
        {title}
      </div>
      {children}
    </div>
  );
}
